// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIdgwXv2VSlEM3ScKFNCJyAtS7RAIAMso',
    appId: '1:181149585288:web:13cbf12ac4530f8b06743d',
    messagingSenderId: '181149585288',
    projectId: 'test2-d827a',
    authDomain: 'test2-d827a.firebaseapp.com',
    databaseURL: 'https://test2-d827a-default-rtdb.firebaseio.com',
    storageBucket: 'test2-d827a.appspot.com',
    measurementId: 'G-J8ZDK1S8B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlksziC5tU3qYW-VXGXlfDRNWdfw8m9kI',
    appId: '1:917250790118:android:358c639cc2f47351602127',
    messagingSenderId: '917250790118',
    projectId: 'test-firebase-9d3a4',
    storageBucket: 'test-firebase-9d3a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6PXNyyGPfYK8G6aTJ4OlvUscv7uotYPU',
    appId: '1:181149585288:ios:fabc09923851a9c706743d',
    messagingSenderId: '181149585288',
    projectId: 'test2-d827a',
    databaseURL: 'https://test2-d827a-default-rtdb.firebaseio.com',
    storageBucket: 'test2-d827a.appspot.com',
    iosBundleId: 'com.example.workerHolic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6PXNyyGPfYK8G6aTJ4OlvUscv7uotYPU',
    appId: '1:181149585288:ios:fabc09923851a9c706743d',
    messagingSenderId: '181149585288',
    projectId: 'test2-d827a',
    databaseURL: 'https://test2-d827a-default-rtdb.firebaseio.com',
    storageBucket: 'test2-d827a.appspot.com',
    iosBundleId: 'com.example.workerHolic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIdgwXv2VSlEM3ScKFNCJyAtS7RAIAMso',
    appId: '1:181149585288:web:94f538f175dd315c06743d',
    messagingSenderId: '181149585288',
    projectId: 'test2-d827a',
    authDomain: 'test2-d827a.firebaseapp.com',
    databaseURL: 'https://test2-d827a-default-rtdb.firebaseio.com',
    storageBucket: 'test2-d827a.appspot.com',
    measurementId: 'G-W13GB0JD6T',
  );
}